- name: Watch for new records
  hosts: localhost
  sources:
    - servicenow.itsm.records:
        instance:
          host: "{{ snow_host | default(omit) }}"
          username: "{{ snow_username | default(omit) }}"
          password: "{{ snow_password | default(omit) }}"
          # timeout: 60
        table: incident
        remote_servicenow_timezone: US/Pacific
  rules:
    - name: New record created
      condition: event.sys_id is defined
      action:
        debug:
